use_frameworks!

target 'UIView-MBProgressHUD_Example' do
  pod 'UIView+YFMBProgressHUD', :path => '../'
  
  target 'UIView-MBProgressHUD_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
